import type { Metadata } from "next";
import "./globals.css";
import AppBar from "@/components/AppBar";
import ReduxProvider from "@/redux/ReduxProvider";
import { AppThemeProvider } from "@/context/AppThemeContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
     
    >
      <body>
        <ReduxProvider>
          <AppThemeProvider>
          <div className="container">
            <AppBar />
            <main>{children}</main>
          </div>
          </AppThemeProvider>
        </ReduxProvider>  
      </body>
    </html>
  );
}